services:
  uptime-kuma:
    build:
      context: .
      dockerfile: docker/dockerfile 
    container_name: kuma
    environment:
      - NODE_ENV=production
      - UPTIME_KUMA_HOST=0.0.0.0
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3003:3003
    restart: unless-stopped
    networks:
      - nginx


networks:
  nginx:
    external: true