services:
  uptime-kuma:
    build:
      context: .
      dockerfile: docker/dockerfile 
    container_name: kuma
    environment:
      - NODE_ENV=production
      - UPTIME_KUMA_HOST=0.0.0.0
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3003:3003
    restart: unless-stopped
    networks:
      - nginx

  tcp-monitor:
    build: 
      context: ./tcpresponder
      dockerfile: Dockerfile
    ports:
      - "50000:50000"  # TCP monitor port
      - "8008:8008"    # API port
    volumes:
      - ./tcpresponder/data:/app/data
    restart: unless-stopped
    environment:
      - NINJA_CLIENT_ID=${NINJA_CLIENT_ID}
      - NINJA_CLIENT_SECRET=${NINJA_CLIENT_SECRET}
      - NINJA_TOKEN_URL=${NINJA_TOKEN_URL}
      - NINJA_SCOPE=${NINJA_SCOPE}
      - NINJA_API_BASE_URL=${NINJA_API_BASE_URL}
    networks:
      - nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/ip"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  mariadb:
    image: mariadb:latest
    container_name: kuma-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-kumapw}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-kuma}
      - MYSQL_USER=${MYSQL_USER:-kuma}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-kumapw}
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - nginx
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-kumapw}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  nginx:
    external: true