version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: docker/debian-base.dockerfile
      target: base2
    image: kuma-backend:base2

  backend:
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: kuma-backend
    user: "node"
    ports:
      - "3003:3003"
    volumes:
      - ./db:/app/db
      - ./data:/app/data
    environment:
      - PORT=3003
      - NODE_ENV=development
      - UPTIME_KUMA_WS_ORIGIN_CHECK=bypass
      - HOST=0.0.0.0
      - UPTIME_KUMA_IS_CONTAINER=1
    networks:
      - nginx
    restart: unless-stopped
    depends_on:
      - base

  frontend:
    build:
      context: .
      dockerfile: docker/dockerfile.frontend
    container_name: kuma-frontend
    ports:
      - "3004:3004"
    environment:
      - VITE_BACKEND_URL=https://kuma.imagenetmit.com
    networks:
      - nginx
    depends_on:
      - backend

networks:
  nginx:
    external: true
