############################################
# Build Base Image
############################################
FROM debian:bookworm-slim AS base2-slim
ARG TARGETPLATFORM

# Install base dependencies
RUN apt update && \
    apt --yes --no-install-recommends install  \
        sqlite3  \
        ca-certificates \
        iputils-ping  \
        util-linux  \
        dumb-init  \
        curl  \
        sudo \
        nscd && \
    rm -rf /var/lib/apt/lists/* && \
    apt --yes autoremove

# Install apprise and python3-paho-mqtt
RUN apt update && \
    apt --yes --no-install-recommends install python3-paho-mqtt && \
    rm -rf /var/lib/apt/lists/* && \
    apt --yes autoremove

# Install cloudflared
RUN curl https://pkg.cloudflare.com/cloudflare-main.gpg --output /usr/share/keyrings/cloudflare-main.gpg && \
    echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared bullseye main' | tee /etc/apt/sources.list.d/cloudflared.list && \
    apt update && \
    apt install --yes --no-install-recommends -t stable cloudflared && \
    cloudflared version && \
    rm -rf /var/lib/apt/lists/* && \
    apt --yes autoremove

# Full Base Image with MariaDB, Chromium and fonts
FROM base2-slim AS base2
ENV UPTIME_KUMA_ENABLE_EMBEDDED_MARIADB=1

# Create node user first
RUN groupadd -r node && useradd -r -g node -m -d /home/node node

# Install Node.js 20
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs

# Install additional dependencies
RUN apt update && \
    apt --yes --no-install-recommends install chromium fonts-indic fonts-noto fonts-noto-cjk mariadb-server && \
    rm -rf /var/lib/apt/lists/* && \
    apt --yes autoremove && \
    chown -R node:node /var/lib/mysql

############################################
# Build in Node.js
############################################
FROM base2 AS build
USER node
WORKDIR /app

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
COPY --chown=node:node .npmrc .npmrc
COPY --chown=node:node package.json package.json
COPY --chown=node:node package-lock.json package-lock.json
RUN npm ci --omit=dev
COPY . .
RUN mkdir ./data

############################################
# ⭐ Main Image
############################################
FROM base2 AS release
WORKDIR /app

LABEL org.opencontainers.image.source="https://github.com/imagenetmit/kuma"

ENV UPTIME_KUMA_IS_CONTAINER=1

# Copy app files from build layer
COPY --chown=node:node --from=build /app /app

EXPOSE 3001
HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD curl -f http://localhost:3001/ || exit 1
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node", "server/server.js"]

############################################
# Rootless Image
############################################
# FROM release AS rootless
# USER node

# ############################################
# # Mark as Nightly
# ############################################
# FROM release AS nightly
# RUN npm run mark-as-nightly

# FROM nightly AS nightly-rootless
# USER node

# ############################################
# # Build an image for testing pr
# ############################################
# FROM louislam/uptime-kuma:base2 AS pr-test2
# WORKDIR /app
# ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1

# ## Install Git
# RUN apt update \
#     && apt --yes --no-install-recommends install curl \
#     && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
#     && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
#     && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
#     && apt update \
#     && apt --yes --no-install-recommends  install git

# ## Empty the directory, because we have to clone the Git repo.
# RUN rm -rf ./* && chown node /app

# USER node
# RUN git config --global user.email "no-reply@no-reply.com"
# RUN git config --global user.name "PR Tester"
# RUN git clone https://github.com/imagenetmit/kuma.git .
# RUN npm ci

# EXPOSE 3000 3001
# HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD extra/healthcheck
# CMD ["npm", "run", "start-pr-test"]

# ############################################
# # Upload the artifact to Github
# ############################################
# FROM louislam/uptime-kuma:base2 AS upload-artifact
# WORKDIR /
# RUN apt update && \
#     apt --yes install curl file

# COPY --from=build /app /app

# ARG VERSION
# ARG GITHUB_TOKEN
# ARG TARGETARCH
# ARG PLATFORM=debian
# ARG FILE=$PLATFORM-$TARGETARCH-$VERSION.tar.gz
# ARG DIST=dist.tar.gz

# RUN chmod +x /app/extra/upload-github-release-asset.sh

# # Full Build
# # RUN tar -zcvf $FILE app
# # RUN /app/extra/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=louislam repo=uptime-kuma tag=$VERSION filename=$FILE

# # Dist only
# RUN cd /app && tar -zcvf $DIST dist
# RUN /app/extra/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=louislam repo=uptime-kuma tag=$VERSION filename=/app/$DIST

